pipeline:
  build-dev:
    image: plugins/docker
    repo: ikifar/whoami
    secrets: [ docker_username, docker_password ]
    tag: [ dev ]
    when:
      branch: dev

  build-prod:
    image: plugins/docker
    repo: ikifar/whoami
    secrets: [ docker_username, docker_password ]
    tag: [ master ]
    when:
      branch: master